### ISSUE TITLE
Create model code

### ISSUE THREAD

**Issue by deSagaz** [edushifts/book-voyage#1]
Define `models.py`. Suggestions for relationships:

![quickdbd-book voyage db v3](https://user-images.githubusercontent.com/4922048/26997927-1dad3154-4d7e-11e7-8012-cb2d4439ad91.png)
*where User is part of the default Django model*

You can adjust the diagram [here](https://app.quickdatabasediagrams.com/#/schema/jI3TCjWU90ip8L8u4yV0FQ) while you go.

Notes:
- BookInstance.accessCode is not used as id any more, since it may be useful to use id in JS and the access code needs to be secret at all times (except for those who have the physical book).
- Handover model informed by [this](https://stackoverflow.com/questions/1110153/what-is-the-most-efficent-way-to-store-a-list-in-the-django-models).
- Coordinate coding informed by [this](https://stackoverflow.com/questions/6345601/django-and-keeping-coordinates)
- Batches are groups of book instances that have been handed out at particular places (e.g., CONANE). The first holder's location and timecode will be derived from this table rather than filled in by them.

**Comment by deSagaz** [comment]
Implementation as of the [previous commit](https://github.com/edushifts/book-voyage/commit/1b8c3e131089c81374bbe73239599c1768958b2a).

![bookvoyage_db_20170612](https://user-images.githubusercontent.com/4922048/27051639-1a8d3c36-4fb7-11e7-945e-46ae0d751723.png)

**Comment by deSagaz** [comment]
**Todo:** the current models code contains a BookLocation.user - this is unnecessary, as user is already tied to a BookHolding.holder.

**Comment by aimahmoiz** [comment]
![quickdbd-book voyage db 1](https://user-images.githubusercontent.com/28938633/27106257-def66508-5092-11e7-9add-c35eef92f30d.png)
Current version of models.py

**Comment by deSagaz** [comment]
Created (hopefully) final model diagram:

![quickdbd-book voyage db_final](https://user-images.githubusercontent.com/4922048/27138266-6aff0888-5120-11e7-9b80-ae579fe10938.png)

Was pushed with commit 54fb1fe91697d90933d57fa4e9770ca6001977dc.

Will move it to the Wiki.

**Comment by deSagaz** [comment]
Code used on the [diagramming website](https://www.quickdatabasediagrams.com/):

```
# Modify the code to update the DB schema diagram.
# To reset the sample schema, replace everything with
# two dots ('..' - without quotes).

Book
-
id PK id
title CharField(64)
authors id FK >-< Author.id
abstract CharField(512)
cover ImageField

Author
-
id PK id
first_name CharField
last_name CharField
date_of_birth DateField
bio TextField

BookInstance
-
id PK id
access_code CharField(64) IDENTITY
book id FK >- Book.id
#finalLat DecimalField # can be empty
#finalLon DecimalField # can be empty
batch id FK >- BookBatch.id
arrived boolean

BookOwning
-
id PK id
owner ForeignKey FK >- User.id
book_instance ForeignKey FK >- BookInstance.id
time DateField
message CharField(512)
location PointField()

BookBatch
-
id PK id
event CharField(64)
country CharField(64)
location Point()
date DateField

BookHolding
-
id PK id
holder ForeignKey FK >- User.id
book_instance ForeignKey FK >- BookInstance.id
#lat DecimalField
#lon DecimalField
time DateField
message CharField(512)
location PointField()

User # Django class
-
DJANGO CLASS
id PK id
username string
first_name string
last_name string
password string
email string

GROUPS # Django class
-
notifications boolean
anonymous boolean



[settings]
Position 155 35
Zoom 100
DefaultFieldType int
CaseSensitive on

[layout]
Book 193 134

BookInstance 447 171

User 808 281
Author -68 150
BookHolding 455 387
BookBatch -55 411
GROUPS 967 406
BookOwning 790 51
```

**Comment by deSagaz** [comment]
See the wiki page [here](https://github.com/edushifts/book-voyage/wiki).

Unless we find grave errors, this Models code is final for v1.0.
