### ISSUE TITLE
GetUserOwnerships()

### ISSUE THREAD

**Issue by deSagaz** [edushifts/book-voyage#12]
Checks whether user is owner of a book, returns data to render. Used on the profile page.

**GetUserOwnerships()**
- Takes `User.id`
- Returns matrix with `BookInstance.id, BookInstance.finalLocation` for each book they own. If no books are owned, an empty matrix is returned instead.

**Comment by deSagaz** [comment]
**Pseudocode by @virtenyatko :**
```
def getUserOwnerships(id):
    for user in User:
        if user.id == id:
            ourUser = user
    result = []
    for book in BookInstance:
        if book.owner == ourUser:
            result.append([book.id,getBookDestination(book.id)])
    return result

**Comment by virtenyatko** [comment]
def getUserOwnerships(id):
    result=[]
    try:
        user = User.objects.get(id=id)
    except User.DoesNotExist:
        user = -1
    try:
        book = BookInstance.objects.get(owner=user).id
        result.append(book)
    return result
