### ISSUE TITLE
Create data policy

### ISSUE THREAD

**Issue by deSagaz** [edushifts/book-voyage#31]
We require a short document outlining that provided data is publicly visible on the platform if a user did not opt-in for anonymity and that we will treat this information with care.

@MarijaPo, perhaps you could help out here, if really no one else volunteers...

**Comment by MarijaPo** [comment]
**Privacy Policy**

EDUshifts is committed to protecting your privacy and ensuring you have a positive experience on our platform.

This policy outlines our handling practices and how we use the personal information you provide.

"Personal Information" is any information that can be used to identify an individual, and may include, but is not limited to name, email address, postal or other physical address.

We do not share your personal information with third parties or for marketing purpose.

The personal information we use, and the way we handle it, includes:

- Location. We collect your location based information for the purpose of the game and the platform. Your location is necessary for the Book Voyage game and therefore cannot be hidden on the platform.
- Your location is securely saved on the platform and cannot be accessed by anybody.
- Postal addresses. These are not retrievable: approximate locations are visible on the platform, but postal addresses themselves are not accessible.
- Name. Your name is saved on the platform and is visible on the platform's map.
- Names can be removed with a checkmark by the admin, or through user's own profile page.
- E-mail addresses. These are at all times confidential, and are only used for e-mails directly from EDUshifts.
- Each e-mail from EDUshifts includes an "unsubscribe" option if you wish to stop receiving updates or other platform related information from us.
-You may also unsubscribe from EDUshifts emails by sending an email, including your name and email address to ahoi@edushifts.world
- No personal data is used anywhere else and is only accessed by the EDUshifts admin.

Should you have any privacy-related questions or comments related to this privacy policy, please send an email to ahoi@edushifts.world


@deSagaz would this work?

**Comment by deSagaz** [comment]
Excellent! Thanks a lot 🥇 

I'll implement it end of the week.

**Comment by deSagaz** [comment]
It's in production now! Only in English, though. If anyone would like it to be translated, they may feel free. For now, I will close this issue.
